.build_template:
  tags:
    - infra-nix-builder
  script:
    - "nix build --print-build-logs .#packages.x86_64-linux.$PACKAGE_NAME"

build_liv-nix-scripts:
  stage: build
  extends: .build_template
  variables:
    PACKAGE_NAME: liv-nix-scripts

build_mango-os:
  stage: build
  extends: .build_template
  variables:
    PACKAGE_NAME: mango-os

build_redscript:
  stage: build
  extends: .build_template
  variables:
    PACKAGE_NAME: redscript

build_rkmod:
  stage: build
  extends: .build_template
  variables:
    PACKAGE_NAME: rkmod
